config/routes.rb
Embedtree::Application.routes.draw do

  match '/oembed', to: 'oembed#index', :as => 'oembed'
  resources :facebook_page

  resources :categories
  resources :pages

  match '/admin', to: 'admin#index', :as => 'admin'
  match '/featured', to: 'posts#featured', :as => 'featured'
  match '/popular', to: 'posts#popular', :as => 'popular'
  match '/facebook', to: 'facebook#index', :as => 'facebook'

  delete 'category_posts/:category_id/:post_id/:user_id', to: 'category_posts#destroy',  :as => 'delete_category_post'
  post 'category_posts/:category_id/:post_id/:user_id', to: 'category_posts#create',  :as => 'create_category_post'

  delete 'category_users/:category_id/:post_id', to: 'category_users#destroy',  :as => 'delete_category_user'
  post 'category_users/:category_id/:post_id', to: 'category_users#create',  :as => 'create_category_user'

 resources :posts do
    collection do
    get :tagged
    end
  end

  match '/posts/:post_id/embed', to: 'embed#show', :as => 'embed' 

  delete 'user_posts/:user_id/:post_id', to: 'user_posts#destroy',  :as => 'delete_user_post'
  post 'user_posts/:user_id/:post_id', to: 'user_posts#create',  :as => 'create_user_post'

  resources :providers, :only => [:show, :index]
  resources :authors, :only => [:show, :index]
  resources :types, :only => [:show, :index]

  authenticated :user do
    root :to => 'posts#index'
  end
  root :to => 'posts#index' 
  devise_for :users
  resources :users

  resources :profiles
  
  scope ":id" do
    get '', to: 'profiles#show', :as => 'vanity_url'
  end

  scope "/facebook/:id" do
    get '', to: 'facebook#show', :as => 'facebook_url'
  end

end

app/views/admin/index.html.erb
<h1>Admin Dashboard</h1>
<hr />
<ul class="nav nav-tabs" id="myTab">
    <li class="active">
        <a href="#users">Users
        </a>
    </li>
    <li class="">
        <a href="#posts">Posts
        </a>
    </li>
    <li class="">
        <a href="#categories">Categories
        </a>
    </li>
    <li class="">
        <a href="#tags">Tags
        </a>
    </li>
</ul>

<div class="tab-content" id="myContent">
  <div class="tab-pane active" id="users">
    <h3>Users</h3>
    <div class="span8">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          <th>Categories Ambassador</th>
          <th>Role</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at.to_date %></td>
          <td>
            <% user.categories.each do |category| %>
              <label class="label label-info"><i class="icon icon-tag icon-white"></i><%= " #{category.name} " %></label>
            <% end %>
         </td>
          <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
          <td>
            <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
            <%= render user %>
          </td>
          <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini btn-danger') unless user == current_user %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>
  </div>

  <div class="tab-pane" id="posts">
    <h3>Posts</h3>

      <table class="table table-condensed">
      <thead>
        <tr>
          <th>Title</th>
          <th>Posts</th>
          <th>Posted Date</th>
          <th>Categories</th>
        </tr>
      </thead>
      <tbody>
      <%  @posts.each do |post| %>
        <tr>
          <td><%= link_to truncate(post.title, :length => 50), post %></td>
          <td><%= post_count(post) %></td>
          <td><%= post.created_at.to_formatted_s(:long_ordinal)  %></td>
          <td><%= post.categories.count %></td>
        </tr>
      <% end %>

      </tbody>
    </table>

        <%#= paginate @posts, :param_name => :posts_page, :remote => true %>

  </div>

  <div class="tab-pane" id="categories">
    <%  @categories.each do |category| %>
      <%= link_to category.name, category %><%= " (#{category.posts.count})" %>
      <hr/>
    <% end %>

  </div>
  <div class="tab-pane" id="tags">
    <%  @tags.sort_by {|tag| tag_posts(tag).count }.reverse.each do |tag| %>
      <%= link_to tag.name, tagged_posts_path(:tag => tag.name) %><%= " (#{tag_posts(tag).count})" %>
      <hr/>
    <% end %>

  </div>

</div>

<script type="text/javascript">

  $('#myTab a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
  })


</script>

app/views/admin/index.js.erb
$("#posts-containter")
.append("<div class='page'><%= escape_javascript(render(@posts)) %></div>");

console.log('replaced');