config/routes.rb
Embedtree::Application.routes.draw do

  match '/oembed', to: 'oembed#index', :as => 'oembed'
  resources :facebook_page

  resources :categories
  resources :pages

  match '/admin', to: 'admin#index', :as => 'admin'
  match '/featured', to: 'posts#featured', :as => 'featured'
  match '/popular', to: 'posts#popular', :as => 'popular'
  match '/facebook', to: 'facebook#index', :as => 'facebook'

  delete 'category_posts/:category_id/:post_id/:user_id', to: 'category_posts#destroy',  :as => 'delete_category_post'
  post 'category_posts/:category_id/:post_id/:user_id', to: 'category_posts#create',  :as => 'create_category_post'

  delete 'category_users/:category_id/:post_id', to: 'category_users#destroy',  :as => 'delete_category_user'
  post 'category_users/:category_id/:post_id', to: 'category_users#create',  :as => 'create_category_user'

 resources :posts do
    collection do
    get :tagged
    end
  end

  match '/posts/:post_id/embed', to: 'embed#show', :as => 'embed' 

  delete 'user_posts/:user_id/:post_id', to: 'user_posts#destroy',  :as => 'delete_user_post'
  post 'user_posts/:user_id/:post_id', to: 'user_posts#create',  :as => 'create_user_post'

  resources :providers, :only => [:show, :index]
  resources :authors, :only => [:show, :index]
  resources :types, :only => [:show, :index]

  authenticated :user do
    root :to => 'posts#index'
  end
  root :to => 'posts#index' 
  devise_for :users
  resources :users

  resources :profiles
  
  scope ":id" do
    get '', to: 'profiles#show', :as => 'vanity_url'
  end

  scope "/facebook/:id" do
    get '', to: 'facebook#show', :as => 'facebook_url'
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId

  attr_accessible :description, :embed_code, :image, 
  :title, :url, :slug, :tag_list, :category_posts_atributes

  validates_format_of :url, :with => URI::regexp(%w(http https))
  validates_presence_of :url, :image

  acts_as_taggable_on :tags

  friendly_id :title, use: :slugged

  has_many :users, :through => :user_posts
  has_many :user_posts

 has_one :provider_post
 has_one :provider, through: :provider_post

 has_one :author_post
 has_one :author, through: :author_post

 has_one :type_post
 has_one :type, through: :type_post

 has_many :category_posts 
 has_many :categories, :through => :category_posts

accepts_nested_attributes_for :categories
accepts_nested_attributes_for :category_posts

paginates_per 5
# max_paginates_per 100

scope :hot,
	select("posts.id, count(user_posts.id) AS user_posts_count").
    joins(:user_posts).
    group("posts.id").
    order("user_posts_count DESC").
    uniq
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource 
  
  include PostsHelper
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at DESC").page(params[:page]).per(6)


    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
      format.json { render json: @posts }
    end
  end

  def featured

    @cat_posts = []
    CategoryPost.all.each do |cp|
      @cat_posts << cp.post
    end
    @cat_posts = @cat_posts.reverse.uniq
    @cat_posts = Kaminari.paginate_array(@cat_posts).page(params[:page]).per(6)

    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
      format.json { render json: @posts }
    end
  end

    def popular

    @hot = Post.hot
    @hot_posts = []
    @hot.each do |hot|
      @hot_posts << Post.find(hot)
    end
    # @hot_posts = @hot_posts.uniq{|x| x.id}
    # debugger
    @hot_posts = Kaminari.paginate_array(@hot_posts).page(params[:page]).per(6)

    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    
    @post = Post.find(params[:id])
    
    respond_to do |format|
          format.html # show.html.erb
          format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @categories_post.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create

    if Post.where(:url => params[:post][:url]) != []
      @post = Post.where(:url => params[:post][:url])[0]
      if UserPost.where(:user_id => current_user, :post_id => @post.id) == [] 
        associate_user 
      end
      respond_to do |format|
        format.html { redirect_to @post, notice: 'Post already exists here... thanks for adding though.' }
          format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    else
     
      @post = Post.new(params[:post])
      unless params[:post][:url] == ""
      embedly(params[:post][:url])
      end

      respond_to do |format|
        if @post.save
          associate_user
          associate_provider
          associate_author
          associate_type
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render json: @post, status: :created, location: @post }
        else
          format.html { redirect_to :back, notice: 'Error posting' }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
     end 

  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  # def tagged
  #   if params[:tag].present? 
  #     @posts = Post.tagged_with(params[:tag])
  #     @tag = params[:tag]
  #   else 
  #     @posts = Post.all
  #   end  
  # end

  def tagged
    if params[:tag].present? 
      @posts = Post.tagged_with(params[:tag]).order("created_at DESC").page(params[:page]).per(6)
      @tag = params[:tag]
      @tags = Post.tag_counts_on(:tags)
      render :action => 'tagged'
     else 
      @posts = Post.all.order("created_at DESC").page(params[:page]).per(6)
    end  
  end

  private 

  def associate_user
    if current_user
      UserPost.create!(:user_id => current_user.id, :post_id => @post.id )
    end
  end

  def associate_provider
    ProviderPost.create!(:post_id => @post.id, :provider_id => @provider.id )
  end

  def associate_author
    AuthorPost.create!(:post_id => @post.id, :author_id => @author.id )
  end

  def associate_type
    TypePost.create!(:post_id => @post.id, :type_id => @type.id )
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
  
	require 'embedly'
  require 'json'

  def associate_tags
    
    require 'nokogiri'
    require 'open-uri'
    require 'open_uri_redirections'

    @post_url = @post.url.sub(/^https?\:\/\//, '')
    @post_url = "http://" + @post_url
  
    @open_url = open(@post_url).read
    @doc = Nokogiri::HTML(@open_url)

    unless @doc.css('meta[name="keywords"], a[rel="tag"][itemprop="keywords"]').to_a == [] || @doc == nil
      @post_tags = @doc.css('meta[name="keywords"], a[rel="tag"][itemprop="keywords"]')[0]['content'].split(",")

      @post_tags.each do |tag|
        @post.tag_list << tag
      end
    end

  end

  def embedly(url)

    embedly_api = Embedly::API.new :key => 'd30e91b2207a40469be014c739c2ddb3', :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; my@email.com)'
    obj = embedly_api.oembed :url => url
    @post.image =  obj[0].thumbnail_url
    @post.embed_code = obj[0].html
    @post.title = obj[0].title
    @post.description = obj[0].description
    associate_tags
   
    @type = Type.find_or_create_by_name(obj[0].type)
    @provider = Provider.find_or_create_by_name_and_url(obj[0].provider_name, obj[0].provider_url)
    @author = Author.find_or_create_by_name_and_url(obj[0].author_name, obj[0].author_url)


  end

  def post_count(post)
      UserPost.where(:post_id => post).count
  end

  def posted(user,post)
    if UserPost.where(:user_id => user.id, :post_id => post.id) != []
      return true
    else
      return false
    end
  end

end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, as: :hidden %>
    <%= f.input :url %>
    <%= f.input :tag_list %>
    <%= f.input :embed_code, as: :hidden %>
    <%= f.input :image, as: :hidden %>
    <%= f.input :description, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="box col3">
    <div class="thumbnail">
     <%= link_to image_tag(post.image), post_path(post)  %>
        <div class="caption">
            <h5><%= link_to post.title.capitalize, post_path(post) if post.title %></h5>
            <p> <%= truncate(post.description, :length => 150) %></p>

            <% if post.provider %>
            <span>On <%= link_to post.provider.name, provider_path(post.provider) if post.provider %></span>
            <% end %>

            <% if post.author %>
            <span> By <%= link_to post.author.name, author_path(post.author) if post.author %></span>
            <% end %>
            <br/>

            <ul class="post_users plull-left">
                <span>via</span>
                  <% post.users.limit(3).each do |user| %>
                    <li><%= link_to user.name, vanity_url_path(user.profile) %> &nbsp;</li>
                  <% end %>
            </ul>

             <hr/>

            <div class="clearfix">
                <p>

                    <label class="label label-mini label-success"><%= pluralize(post_count(post), 'Post') %></label>
                    <% if post.type %>
                    <label class="label label-mini label-<%= post.type.name %>"><%= link_to post.type.name.capitalize, type_path(post.type) %></label>
                    <% end %>

                    <% if post.categories.any? %>
                        <% post.categories.each do |category| %>
                           <label class="label label-mini label-info">
                            <i class="icon icon-white icon-tag"></i>
                            <%= link_to "#{category.name}", category_url(category)%></label>
                        <% end %>
                    <% end %>


                </p>

                <% if post.tags.any? %>
                  <p>
                    <% post.tags.each do |tag| %>
                      <span><%= link_to "##{tag.name}", tagged_posts_path(:tag => tag.name) %></span>
                    <% end %>
                  </p>
                <% end %>

                <% if current_user %>
                    <hr/>
                    <span class="pull-left">
                    <% if can? :manage, @post %>
                    <%= link_to 'Edit', edit_post_path(post), :class => "btn  btn-mini btn-primary" %>
                    <%= link_to 'Kill', post, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %>
                    <% end %>
                    </span>

                    <% if posted(current_user, post) %>
                    <span class="pull-right">
                    <%= link_to 'Delete', delete_user_post_path(current_user.id,post.id),
                     :remote => true, method: :delete, :class => "btn btn-mini btn-warning pull-right delete_user_post" %>
                     <%= link_to 'Post', create_user_post_path(current_user.id,post.id),
                     :remote => true, method: :post, :class => "btn btn-mini btn-success pull-right user_post hidden" %>
                    </span>
                     <% else %>
                     <span class="pull-right">
                     <%= link_to 'Post', create_user_post_path(current_user.id,post.id),
                     :remote => true, method: :post, :class => "btn btn-mini btn-success pull-right user_post" %>
                     <%= link_to 'Delete', delete_user_post_path(current_user.id,post.id),
                     :remote => true, method: :delete, :class => "btn btn-mini btn-warning pull-right delete_user_post hidden" %>
                   </span>
                     <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/featured.html.erb
<div class="row text-center">
	<h1 class=''>Latest Leaves</h1>
	<hr/>

  <div class="pull-center">
    <ul class="nav nav-pills">
      <li class=""><a href="/">All</a></li>
      <li class="active"><a href="featured">Featured</a></li>
      <li class=""><a href="popular">Popular</a></li>
    </ul>
  </div>

      <div id="masonry-container" class="transitions-enabled centered infinite-scroll clearfix masonry">
          <% @cat_posts.each do |post| %>
            <%= render 'shared/tree', :post => post %>
          <% end %>
      </div>

      <div id="paginator">
        <%= paginate @cat_posts %>
      </div>

</div>



<script type="text/javascript">

$(function(){ 

  $('#myTab a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })

  var $container = $('#masonry-container');

  $container.infinitescroll({
    navSelector  : '.pagination',    // selector for the paged navigation 
    nextSelector : '.pagination a[rel=next]',  // selector for the NEXT link (to page 2)
    itemSelector : '.box',     // selector for all items you'll retrieve
    loading: {
        finishedMsg: 'No more pages to load.',
        img: 'http://i.imgur.com/6RMhx.gif'
      }
    },
    // trigger Masonry as a callback
    function( newElements ) {
      // hide new items while they are loading
      var $newElems = $( newElements ).css({ opacity: 0 });
      // ensure that images load before adding to masonry layout


      $newElems.imagesLoaded(function(){
        // show elems now they're ready
        $newElems.animate({ opacity: 1 });
        $container.masonry( 'appended', $newElems, true ); 

      });
    }
  );
  console.log( "posts!" );

 });

 
</script>

app/views/posts/index.html.erb
<div class="row text-center">
	<h1 class=''>Latest Leaves</h1>
	<hr/>

  <div class="pull-center">
    <ul class="nav nav-pills">
      <li class="active"><a href="/">All</a></li>
      <li class=""><a href="featured">Featured</a></li>
      <li class=""><a href="popular">Popular</a></li>
    </ul>
  </div>

      <div id="masonry-container" class="transitions-enabled centered infinite-scroll clearfix masonry">
          <% @posts.each do |post| %>
            <%= render 'shared/tree', :post => post %>
          <% end %>
      </div>

      <div id="paginator">
        <%= paginate @posts %>
      </div>

</div>



<script type="text/javascript">

$(function(){ 

  $('#myTab a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })


  
 
</script>

app/views/posts/index.js.erb
$("#masonry-container")
.append("<div class='page'><%= escape_javascript(render(@posts)) %></div>");

console.log('add');

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/popular.html.erb
<div class="row text-center">
	<h1 class=''>Latest Leaves</h1>
	<hr/>

  <div class="pull-center">
    <ul class="nav nav-pills">
      <li class=""><a href="/">All</a></li>
      <li class=""><a href="featured">Featured</a></li>
      <li class="active"><a href="popular">Popular</a></li>
    </ul>
  </div>

      <div id="masonry-container" class="transitions-enabled centered infinite-scroll clearfix masonry">
          <% @hot_posts.each do |post| %>
            <%= render 'shared/tree', :post => post %>
          <% end %>
      </div>

      <div id="paginator">
        <%= paginate @hot_posts %>
      </div>

</div>



<script type="text/javascript">

$(function(){ 

  $('#myTab a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })

  var $container = $('#masonry-container');

  $container.infinitescroll({
    navSelector  : '.pagination',    // selector for the paged navigation 
    nextSelector : '.pagination a[rel=next]',  // selector for the NEXT link (to page 2)
    itemSelector : '.box',     // selector for all items you'll retrieve
    loading: {
        finishedMsg: 'No more pages to load.',
        img: 'http://i.imgur.com/6RMhx.gif'
      }
    },
    // trigger Masonry as a callback
    function( newElements ) {
      // hide new items while they are loading
      var $newElems = $( newElements ).css({ opacity: 0 });
      // ensure that images load before adding to masonry layout


      $newElems.imagesLoaded(function(){
        // show elems now they're ready
        $newElems.animate({ opacity: 1 });
        $container.masonry( 'appended', $newElems, true ); 

      });
    }
  );
  console.log( "posts!" );

 });

 
</script>

app/views/posts/show.html.erb
<% content_for :head do %>

  <meta name="twitter:card" content="player">
<meta name="twitter:site" content="@embedtree">
<meta name="twitter:creator" content="@embedtree">
<meta name="twitter:title" content="<%= @post.title %>">
<meta name="twitter:description" content="<%= @post.description %>">
<meta name="twitter:image:src" content="<%= @post.image %>">
<meta name="twitter:player" content="<%= @post.embed_code.gsub(/["]/, "'").html_safe %>">
<meta name="twitter:player:height" content="300">
<meta name="twitter:player:width" content="300 ">
<meta name="twitter:domain" content="www.embedtree.com">

<meta property="og:site_name" content="EmbedTree" />
<meta property="og:url" content="<%= post_url(@post) %>" />
<meta property="og:title" content="<%= @post.title %>" />
<meta property="og:type" content="<%= @post.type.name %>" />
<meta property="og:image" content="<%= @post.image %>" />
<meta property="og:description" content="<%= @post.description %>" />
<meta property="og:video" content="<%= embed_url(@post)%>" />
<!-- <meta property="og:video:type" content="application/x-shockwave-flash" />
<meta property="og:video:width" content="1280" />
<meta property="og:video:height" content="720" />
<meta property="fb:app_id" content="87741124305" /> -->


  <link rel="alternate" type="application/json+oembed"
  href="/oembed?url=<%= post_path(@post) %>&format=json"
  title="#{@post.title}" />
<% end %>

  <article class="row">

   <section class="span10">
      <h1>
          <% if @post.title != "" %>
            <%= link_to @post.title, @post.url, :target => "_blank"  %>
          <% else %>
            <%= link_to truncate(@post.url, :length => 25), @post.url, :target => "_blank"  %>
          <% end %>
      </h1>
      <hr/>
    </section>

  <section class="span7">
  
  <div id="" class="flex-video widescreen">
        <% if @post.embed_code %>
          <%= @post.embed_code.html_safe %>
        <% elsif @post.image %>
          <%= image_tag(@post.image) %>
        <% else %>
          <p class="well" >Sorry, there is no embed code.</p> 
        <% end %>
  </div>


    <% if @post.description != "" %>
      <p class="well">
        <%= @post.description %>
      </p>
    <% else %>
    <% end %>

    <% if current_user %>
     <% if posted(current_user, @post) %>
        <span class="pull-left">
        <%= link_to 'Un-Post', delete_user_post_path(current_user.id, @post.id),
         :remote => true, method: :delete, :class => "btn btn-mini pull-right delete_user_post" %>
         <%= link_to 'Post', create_user_post_path(current_user.id, @post.id),
         :remote => true, method: :post, :class => "btn btn-mini btn-success pull-right user_post hidden" %>
        </span>
         <% else %>
         <span class="pull-left">
         <%= link_to 'Post', create_user_post_path(current_user.id, @post.id),
         :remote => true, method: :post, :class => "btn btn-mini btn-success pull-right user_post" %>
         <%= link_to 'Un-Post', delete_user_post_path(current_user.id, @post.id),
         :remote => true, method: :delete, :class => "btn btn-mini pull-right delete_user_post hidden" %>
       </span>
     <% end %>
    <% end %>

  </section>
  <side class="span3">

    <section>
      <%= link_to image_tag(@post.image), @post.url, :class => "thumbnail" if @post.image %>
      <br/>
      <p>
        <% if @post.provider %>
        <span>On <%= link_to @post.provider.name, provider_path(@post.provider) %></span>
        <% end %>
        <% if @post.author %>
        <span> By <%= link_to @post.author.name, author_path(@post.author) %></span>
        <% end %>
      </p>
    </section>

        <section>

        <p>Via
          <% @post.users.limit(3).each do |user| %>
            <span><%= link_to user.name, vanity_url_path(user.profile) %></span>
          <% end %>
        </p>
    </section>

    <section>
      <p>
      <label class="label label-mini label-success"><%= pluralize(post_count(@post), 'post') %></label>
      <label class="label label-mini label-<%= @post.type.name %>"><%= link_to @post.type.name, type_path(@post.type) %></label>

      <div id="category_labels">
        <%= render :partial => "category_posts/category_labels", :post => @post %>
      </div>

    </p>
    </section>

    <hr/>

    <section>
      <% if @post.tags.any? %>
      <p>Tags:
          <% @post.tags.each do |tag| %>
          <span><%= link_to "##{tag.name}", tagged_posts_path(:tag => tag.name) %></span>
        <% end %>
      </p>

      <% end %>

      <% if can? :manage, @post %>
        <p>Edit Tags:</p>
       <%= simple_form_for(@post) do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.text_area :tag_list, :cols => 4, :rows => 3, :class => "span3", :stye => "height: 80px;" %>
            <%= f.button :submit, :value => "Add Tags", :class => "btn btn-mini" %>
          </div>
        <% end %>
         <%= link_to 'Edit', edit_post_path(@post) %>
      <% end %>

    </section>


  </side>

</article>

app/views/posts/tagged.html.erb
<div class="row text-center">
	<h1 class=''><%= pluralize(@posts.count, 'Post') %> Tagged : <%= @tag.capitalize %></h1>
	<hr/>


	<div id="masonry-container" class="transitions-enabled centered clearfix masonry">
	    <% @posts.reverse.each do |post| %>
	      <%= render 'shared/tree', :post => post %>
	    <% end %>
	</div>

	<%= paginate @posts %>
</div>