config/routes.rb
Embedtree::Application.routes.draw do

  match '/oembed', to: 'oembed#index', :as => 'oembed'
  resources :facebook_page

  resources :categories
  resources :pages

  match '/admin', to: 'admin#index', :as => 'admin'
  match '/featured', to: 'posts#featured', :as => 'featured'
  match '/popular', to: 'posts#popular', :as => 'popular'
  match '/facebook', to: 'facebook#index', :as => 'facebook'

  delete 'category_posts/:category_id/:post_id/:user_id', to: 'category_posts#destroy',  :as => 'delete_category_post'
  post 'category_posts/:category_id/:post_id/:user_id', to: 'category_posts#create',  :as => 'create_category_post'

  delete 'category_users/:category_id/:post_id', to: 'category_users#destroy',  :as => 'delete_category_user'
  post 'category_users/:category_id/:post_id', to: 'category_users#create',  :as => 'create_category_user'

 resources :posts do
    collection do
    get :tagged
    end
  end

  match '/posts/:post_id/embed', to: 'embed#show', :as => 'embed' 

  delete 'user_posts/:user_id/:post_id', to: 'user_posts#destroy',  :as => 'delete_user_post'
  post 'user_posts/:user_id/:post_id', to: 'user_posts#create',  :as => 'create_user_post'

  resources :providers, :only => [:show, :index]
  resources :authors, :only => [:show, :index]
  resources :types, :only => [:show, :index]

  authenticated :user do
    root :to => 'posts#index'
  end
  root :to => 'posts#index' 
  devise_for :users
  resources :users

  resources :profiles
  
  scope ":id" do
    get '', to: 'profiles#show', :as => 'vanity_url'
  end

  scope "/facebook/:id" do
    get '', to: 'facebook#show', :as => 'facebook_url'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	extend FriendlyId
  attr_accessible :name, :slug

  validates_uniqueness_of :name

  friendly_id :name, use: :slugged

  has_many :posts, :through => :category_posts
	has_many :category_posts

	has_many :users, :through => :category_users
	has_many :category_users


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @posts = @category.posts.order("created_at DESC").page(params[:page]).per(6)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :slug, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<br />
<%= link_to 'New Category', new_category_path, :class => "btn btn-mini pull-right" if can? :manage, Category %>
<br />

<h1>All Categories</h1>
<hr/>

<div class="row">
	<% @categories.each do |category| %>
		<div class="span3">
	   <h2>
	   	<%= image_tag(category.posts.first.image, :width => "50px") if category.posts != []  %>
	   	<%= link_to category.name, category %>
	   </h2>
	   

	   <% if can? :manage, Category %>
	   <br/>
	   <%= link_to 'Edit', edit_category_path(category) %>
	   <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
	   <% end %>
	 </div>
	<% end %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%= link_to 'Edit', edit_category_path(@category), :class => "pull-right" if can? :manage, Category %>
<br/>

<h1 class="text-center">
  <%= @category.name %>
</h1>

<h3>Edited by: 	
	<% @category.users.each do |user| %>

		<%= link_to image_tag(user.profile.image.url(:thumb) || "embedtree-logo.png", :width => "35px", :class => "img-circle"), vanity_url_path(user)  %>
	<% end %>
</h3>

<hr />

<div id="masonry-container" class="transitions-enabled centered text-center clearfix masonry">

	<% @posts.each do |post| %>
		<%= render 'shared/tree', :post => post %>
	<% end %>

</div>

<%= paginate @posts %>

<script type="text/javascript">

$('#example').tooltip(options);

</script>